// <auto-generated />
using FanCentral.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FanCentral.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191108101811_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("FanCentral.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accessories")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Brand")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Clearance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Collectibles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Custom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hats")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HomeAndOffice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Jersies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Kids")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Men")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Minshew")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NFL100")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Players")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Retired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Salute")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Season25")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Shirts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sideline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sweatshirts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WearCollection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Women")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
